- reporting/redapi.py
I should have been a Reddit Engineer to change divs to buttons instead of actually making an API for the advertiser that make the platform possible
> Reddit Update

- reporting/pmapi.py
Initialize browser for each VM line, remove timeout, log Pathmatics title found
> PMAPI Update

- reporting/pmapi.py
Add creative metric and URL pulling. Add publisher/brand filter via search result order. Increased logging.
> Pmapi creative pulling

- reporting/rsapi.py
I really did try to add a newline
> rsapi adding apifields function

- reporting/analyze.py
Currently checks CTR w/ Kevin's benchmarks as well as metrics.
> Setup flagging structure for abnormal metrics in Analyze.

- reporting/dbapi.py
& Clean up function structures to mirror other API setups.
> Add viewability optionality in fields. 

- reporting/vendormatrix.py
Add functionality to FilterCol that allows for an inverse or exclusionary filter. Usage: FilterCol::col_name::col_val::Exclude
> Add 'not in' filter functionality to 'FilterCol' transform type

- reporting/dictionary.py
- reporting/vendormatrix.py
Update dictionary/vendormatrix functionality to allow construction of required dataframe for change autodict order modal
> Processor autodictorder update

- reporting/analyze.py
+ minor changes to project_delv_completion.
> Patch double_counting proportions.

- reporting/analyze.py
Use utl.import_read_csv filename handling and existence check
> Rework get_column_names_from_raw_files to allow for xlsx files

- reporting/dictionary.py
- reporting/utils.py
Prevent potential duplication due to '-1' append on duplicate rename.
> Prevent persistent duplicated columns in autodictionary

- reporting/analyze.py
- reporting/vendormatrix.py
Do column-checking auto analysis on transformed data to allow for possibility of transformed column names.
> Use transformed data in autoanalysis col checks

- reporting/scapi.py
Age and/or gender OR country dimensions can be imported from Snapchat via API Fields.
> Allow import of age, gender, or country dimensions in Snapchat

- reporting/utils.py
Allow for a column filled by values from separate column(s) to have multiple rules applied.
> Allow multiple rule operations on copied column values

- reporting/tikapi.py
'complete_payment' and 'user_registration'
> Add addtional conversion metrics to tik tok api

- reporting/tikapi.py
Landing page -> time_attr_view
> Add landing page conversion metric to tikapi

- reporting/dcapi.py
> added adId to default fields

- reporting/dcapi.py
Update DCM API from version 3.5 -> 4.
> Update DCM version

- reporting/importhandler.py
Fix allows for use of API_MERGE functionality.
> Use full_file in merge_df to guarantee correct file path

- reporting/awapi.py
- reporting/vmcolumns.py
> AWapi test connection edits

- reporting/dictionary.py
- reporting/vendormatrix.py
Change append to concat in vm and dict update scripts.
> Update run pandas update

- reporting/export.py
- tests/test_unit.py
Also add unit testing to several ScriptBuilder methods
> Add helper function in ScriptBuilder to check metric names against event tables

- reporting/nzapi.py
Resolve missing value mis-match. Resolve output dataframe merge issues.
> Newzoo API fixes

- reporting/amzapi.py
AmzApi updated Sponsored Products reports to v3 endpoint with jessicaleviton and Casasro
> Amazon api update

- reporting/scapi.py
- reporting/utils.py
Added Test connection functionality to snapchat api
1/3 added get_campaign_ids helper function, added vmc import
> Sctestconnect

- reporting/ttdapi.py
Adding ValueError exception in get_dwonload_url function and if statement in get_data function in order to avoid dowloading empty report from TTD API.
> Adding ValueError exception in get_dwonload_url function

- reporting/ttdapi.py
TTD Adding check_partner_id and advertiser_id
> TTD test_connection

- reporting/criapi.py
- reporting/vmcolumns.py
> Critestconnect

- reporting/ttdapi.py
> TTD correcting functions

- reporting/dcapi.py
option to insert into fields. If included data will download platformType dimension
> platformType - more precise environment 

- reporting/redapi.py
> Redapi Test Connection

- reporting/simapi.py
updated functions to have error and data check, prevent overspending credits
4/2/2024
> Similar Web Batch API.

- reporting/ajapi.py
Nikki and Alexei want to use 'network installs', 'organic installs', 'skad installs' for the dashboard of a new client called 13 games. The campaign will last several months
> New variables (def_fields) for Adjust

- main.py
- reporting/importhandler.py
- reporting/simapi.py
- reporting/vendormatrix.py
- reporting/vmcolumns.py
5/30/2024
resolve merge conflicts, add api key to vmcolumns
> Simweb update

- reporting/simapi.py
add fields arg to get_data function
6/6/2024
> add fields arg to get_data function

- reporting/vmcolumns.py
Adding api_rs_key, api_red_key and api_ttd_key to test_apis
> Adding Apis to test_apis

- reporting/redapi.py
Added Keys and ActionChains to Import
> Reddit api fix

- reporting/analyze.py
- reporting/utils.py
Catch for NaN not being a string
> analyze.py CheckAutoDictOrder bug catch

- tests/test_end.py
- tests/test_unit.py
Added docstrings for some tests giving debug suggestions for tricky errors
> Added docstrings for some tests

- reporting/awapi.py
add engagement metric to default metrics. 
10/29/204
> add engagement metrics to default metrics.

- reporting/gaapi.py
now the regex filters will be applied if the user wants to
> made filter optional

- reporting/redapi.py
> Redapi error fixes

- reporting/redapi.py
Changed xpath for customize columns to get button text
> RedApi error fix

- reporting/importhandler.py
- reporting/redapi.py
- makes import continue running if red fail occurs
> Removed system exits in redapi.py and added check to importhandler.py

- reporting/analyze.py
- reporting/awapi.py
- tests/test_unit.py
> adwords split function in analyze.py

- reporting/tikapi.py
add engagement click metrics to default metrics for tikapi. 
11/22/2024
> add engagement click metrics to default metrics for tikapi.

- reporting/utils.py
- added clean_monetary_input function to reporting/utils.py
> Monetary formatting helper

- reporting/amzapi.py
check if dfs are not none or empty before concat
> error handling in amzapi.py

- reporting/tikapi.py
> Tiktok new metric

- reporting/redapi.py
check data exists in redapi get_all_business_ids
> redapi keyerror fix

- reporting/analyze.py
- reporting/utils.py
- tests/test_unit.py
- modify flag_errant_metrics to check for VCR and adserving v. platform clicks (reporting/analyze.py)
- add test that runs sample data through analysis to trigger each metric check (tests/test_unit.py)
> Add error metric checks

- reporting/rsapi.py
in get_raw_data add loop and remove unused code
> rsapi.py bugfix

- reporting/redapi.py
Add custom conversions to reports
> Redapi add conversions

- reporting/utils.py
add choose_existing parameter to send_keys_from_list to account for choosing a pre-defined option from dropdown (reporting/utils.py)
> fix dcm test

- reporting/ttdapi.py
-dynamically switch between report name and campaign IDs using regex
-allow for multiple campaign IDs
> Ttd create report

- reporting/awss3.py
- reporting/gsapi.py
- remove duplicate property (reporting/awss3.py)
- change image processing of google docs to upload and reference them using s3 (reporting/gsapi.py)
> Tutorial image permissions

- reporting/iasapi.py
fixed xpath for title filtering, added additional metric for download, switched dates in report name
> API fix, metric addition, report name modification

- reporting/analyze.py
Clean up returns and simplify some logic
> find_first_row update

- reporting/gsapi.py
cleanup google doc image naming/keys, switch to nonpresigned urls (reporting/gsapi.py)
> Tutorial images
